dist: bionic
language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install: pip install tox tox-travis coverage codecov
script: tox --recreate
branches:
  except:
  - "/^\\d/"
after_success:
- codecov
notifications:
  email:
  - bubenkoff@gmail.com
  - oleg.pidsadnyi@gmail.com
